-- ============================================================================
-- PourCastAI - SHARED DATABASE SCHEMA  (Step 1: "the contract")
-- ============================================================================
-- One SQLite file, opened by BOTH agents. Because it is one physical file with
-- ONE set of dimension tables, the two agents can never disagree about what
-- item 26827 or store 2633 is. That is what "shared database, no mismatch"
-- actually means in practice.
--
-- The two keys that tie everything together are:
--     item_number   (a product / SKU)
--     store_number  (a retail store)
-- Every fact table references these SAME keys. Do not rename them.
--
-- REAL      = comes straight from the Iowa Liquor Sales dataset (Kaggle)
-- SIMULATED = generated by us (clearly labelled, for the report's methodology)
-- ============================================================================

PRAGMA foreign_keys = ON;

-- ----------------------------------------------------------------------------
-- DIMENSIONS  (the shared core - read by BOTH agents)
-- ----------------------------------------------------------------------------

-- dim_vendor : the supplier of a product. (Iowa is a control state, so the
-- vendor is the brand owner whose stock sits in the Ankeny state warehouse.)
DROP TABLE IF EXISTS dim_vendor;
CREATE TABLE dim_vendor (
    vendor_number      INTEGER PRIMARY KEY,   -- REAL
    vendor_name        TEXT,                  -- REAL
    lead_time_days     INTEGER,               -- SIMULATED (2-10 days to restock)
    lead_time_std      REAL,                  -- SIMULATED (assumed 20% of lead_time_days -
                                               -- no public dataset tracks real delivery-time
                                               -- variance, so this is a documented estimate,
                                               -- same approach as the sensitivity-tested
                                               -- lead_time_avg assumption elsewhere)
    reliability_score  REAL                   -- SIMULATED (0.85-0.99, on-time rate)
);

-- dim_item : one row per product / SKU.
DROP TABLE IF EXISTS dim_item;
CREATE TABLE dim_item (
    item_number        INTEGER PRIMARY KEY,   -- REAL  <-- shared key
    item_description   TEXT,                  -- REAL
    category           INTEGER,               -- REAL
    category_name      TEXT,                  -- REAL
    vendor_number      INTEGER,               -- REAL  (links to dim_vendor)
    pack               INTEGER,               -- REAL  (bottles per case)
    bottle_volume_ml   INTEGER,               -- REAL
    state_bottle_cost  REAL,                  -- REAL  (wholesale cost)
    state_bottle_retail REAL,                 -- REAL  (shelf price)
    FOREIGN KEY (vendor_number) REFERENCES dim_vendor(vendor_number)
);

-- dim_store : one row per retail store. Has REAL lat/long, which the Risk
-- agent needs to route Ankeny -> store.
DROP TABLE IF EXISTS dim_store;
CREATE TABLE dim_store (
    store_number       INTEGER PRIMARY KEY,   -- REAL  <-- shared key
    store_name         TEXT,                  -- REAL
    address            TEXT,                  -- REAL
    city               TEXT,                  -- REAL
    zip_code           TEXT,                  -- REAL
    county_number      INTEGER,               -- REAL
    county             TEXT,                  -- REAL
    latitude           REAL,                  -- REAL  (destination for routing)
    longitude          REAL,                  -- REAL
    population         INTEGER,               -- REAL (US Census ACS5, county-level;
                                               -- fetched once at build time, not per-request -
                                               -- population doesn't change day to day)
    rural_flag         INTEGER                -- DERIVED (population < 20,000 = rural;
                                               -- a documented simplification, not an official
                                               -- USDA Rural-Urban Continuum Code)
);

-- dim_carrier : who drives the truck. Ruan is the real carrier for Iowa ABD;
-- the extra rows are simulated so the scorecard has something to compare.
DROP TABLE IF EXISTS dim_carrier;
CREATE TABLE dim_carrier (
    carrier_id         INTEGER PRIMARY KEY,   -- SIMULATED
    carrier_name       TEXT                   -- Ruan is real; others simulated
);

-- ----------------------------------------------------------------------------
-- FACTS
-- ----------------------------------------------------------------------------

-- fact_sales : REAL transactions from the Iowa dataset. One row per sale line.
DROP TABLE IF EXISTS fact_sales;
CREATE TABLE fact_sales (
    sale_id            INTEGER PRIMARY KEY AUTOINCREMENT,
    sale_date          TEXT,                  -- REAL (YYYY-MM-DD)
    store_number       INTEGER,               -- REAL  (links to dim_store)
    item_number        INTEGER,               -- REAL  (links to dim_item)
    vendor_number      INTEGER,               -- REAL
    bottles_sold       INTEGER,               -- REAL
    sale_dollars       REAL,                  -- REAL
    volume_sold_liters REAL,                  -- REAL
    FOREIGN KEY (store_number) REFERENCES dim_store(store_number),
    FOREIGN KEY (item_number)  REFERENCES dim_item(item_number)
);

-- fact_inventory_snapshot : SIMULATED, but DERIVED FROM real sales.
-- One row per store x item x day. This is the Inventory agent's world.
-- "on_hand" is depleted each day by REAL bottles_sold and refilled by orders.
DROP TABLE IF EXISTS fact_inventory_snapshot;
CREATE TABLE fact_inventory_snapshot (
    snapshot_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_date      TEXT,                  -- SIMULATED day (YYYY-MM-DD)
    store_number       INTEGER,               -- (shared key -> dim_store)
    item_number        INTEGER,               -- (shared key -> dim_item)
    on_hand_bottles    INTEGER,               -- SIMULATED stock level
    reorder_point      INTEGER,               -- SIMULATED (statistical safety-stock model -
                                               -- see simulate.py reorder_point())
    safety_stock       INTEGER,               -- SIMULATED (buffer component of reorder_point,
                                               -- stored separately so the UI/report can show
                                               -- "why" the threshold is what it is)
    days_of_cover      REAL,                  -- SIMULATED (on_hand / daily demand)
    FOREIGN KEY (store_number) REFERENCES dim_store(store_number),
    FOREIGN KEY (item_number)  REFERENCES dim_item(item_number)
);

-- fact_shipments : SIMULATED inbound replenishment orders (Ankeny -> store).
-- One row per order the simulation places when stock crosses the reorder point.
-- This is the Risk & Logistics agent's world.
DROP TABLE IF EXISTS fact_shipments;
CREATE TABLE fact_shipments (
    shipment_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    order_date         TEXT,                  -- SIMULATED (YYYY-MM-DD)
    promised_eta       TEXT,                  -- SIMULATED (order_date + lead time)
    store_number       INTEGER,               -- (shared key -> dim_store) destination
    item_number        INTEGER,               -- (shared key -> dim_item)
    vendor_number      INTEGER,               -- REAL vendor of the item
    carrier_id         INTEGER,               -- SIMULATED (links to dim_carrier)
    quantity_bottles   INTEGER,               -- SIMULATED order size
    origin_lat         REAL,                  -- Ankeny warehouse (fixed, real coords)
    origin_long        REAL,
    dest_lat           REAL,                  -- store lat (REAL, from dim_store)
    dest_long          REAL,
    FOREIGN KEY (store_number)  REFERENCES dim_store(store_number),
    FOREIGN KEY (item_number)   REFERENCES dim_item(item_number),
    FOREIGN KEY (carrier_id)    REFERENCES dim_carrier(carrier_id)
);

-- ext_cache : small key/value cache that n8n writes into on a schedule
-- (e.g. diesel price every 30 min). risk_tools.py reads this FIRST, before
-- calling the live API, so per-question latency doesn't depend on an
-- external API responding inside a chat turn. Not wiped by simulate.py.
DROP TABLE IF EXISTS ext_cache;
CREATE TABLE ext_cache (
    cache_key   TEXT PRIMARY KEY,   -- e.g. 'diesel_price'
    value       TEXT,               -- stored as text, parsed by the reader
    fetched_at  TEXT                -- ISO timestamp, so staleness is checkable
);

-- ----------------------------------------------------------------------------
-- GOLD VIEWS  (ready-to-use joins - one per agent)
-- ----------------------------------------------------------------------------

-- What the Inventory agent reads: latest snapshot per store x item, flagged low.
DROP VIEW IF EXISTS gold_inventory_health;
CREATE VIEW gold_inventory_health AS
SELECT
    s.snapshot_date,
    s.store_number,
    st.store_name,
    st.county,
    s.item_number,
    it.item_description,
    it.vendor_number,
    s.on_hand_bottles,
    s.reorder_point,
    s.safety_stock,
    s.days_of_cover,
    it.state_bottle_cost,
    it.state_bottle_retail,
    ROUND(s.on_hand_bottles * it.state_bottle_retail, 2) AS inventory_value,
    CASE WHEN s.on_hand_bottles <= s.reorder_point THEN 1 ELSE 0 END AS low_stock_flag
FROM fact_inventory_snapshot s
JOIN dim_store st ON st.store_number = s.store_number
JOIN dim_item  it ON it.item_number  = s.item_number
-- most recent snapshot only:
WHERE s.snapshot_date = (SELECT MAX(snapshot_date) FROM fact_inventory_snapshot);

-- What the Risk agent reads: open inbound shipments with route + carrier info.
DROP VIEW IF EXISTS gold_shipments_open;
CREATE VIEW gold_shipments_open AS
SELECT
    sh.shipment_id,
    sh.order_date,
    sh.promised_eta,
    sh.store_number,
    st.store_name,
    st.county,
    st.population,
    st.rural_flag,
    sh.item_number,
    it.item_description,
    it.state_bottle_retail,
    ROUND(sh.quantity_bottles * it.state_bottle_retail, 2) AS shipment_value,
    sh.vendor_number,
    v.vendor_name,
    v.reliability_score,
    sh.carrier_id,
    c.carrier_name,
    sh.quantity_bottles,
    sh.origin_lat, sh.origin_long,
    sh.dest_lat,   sh.dest_long
FROM fact_shipments sh
JOIN dim_store   st ON st.store_number  = sh.store_number
JOIN dim_item    it ON it.item_number   = sh.item_number
JOIN dim_vendor  v  ON v.vendor_number  = sh.vendor_number
JOIN dim_carrier c  ON c.carrier_id     = sh.carrier_id;
